export type Category =
  | "supplements"
  | "aromatics"
  | "stones"
  | "apparel"
  | "books-audio"
  | "digital";

export type Product = {
  slug: string;
  sku: string;
  name: string;
  priceCents: number;
  category: Category;
  image: string;
  blurb: string;
  description: string;
  benefits: string[];
  size: string;
  dose?: string;
  bestseller?: boolean;
  digital?: boolean;
  subscribeEligible?: boolean;
  phase: 1 | 2;
  onHand: number;
  rfqUnits: number;
  cogsLow: number;
  cogsHigh: number;
  notes: string;
  servings?: string;
};

export const CATEGORIES: { id: Category; label: string; pillar: string; copy: string }[] =
  [
    {
      id: "supplements",
      label: "Supplements",
      pillar: "Find Love",
      copy: "cGMP capsules. The line you can take home today.",
    },
    {
      id: "aromatics",
      label: "Ritual",
      pillar: "Be Love",
      copy: "Incense, smoke, wax, mist. Highest turns in metaphysical retail — if the sourcing is clean.",
    },
    {
      id: "stones",
      label: "Stones & Jewelry",
      pillar: "Find Love",
      copy: "Five stones. Three jewels. Not a crystal mall. Rose quartz is the love stone — it is on-brand.",
    },
    {
      id: "apparel",
      label: "Apparel",
      pillar: "Share Love",
      copy: "Tee, cap, tote first. Hoodie after the tee proves size mix. The mark is small.",
    },
    {
      id: "books-audio",
      label: "Paper",
      pillar: "Find Love",
      copy: "House journal and the 30-day deck. Do not resell books Amazon already owns.",
    },
    {
      id: "digital",
      label: "Digital",
      pillar: "Be Love",
      copy: "The 30-day library is free in the companion. Paid titles when they exist.",
    },
  ];

export const PRODUCTS: Product[] = [

  {
    slug: "magnesium-complex",
    sku: "BL-MG-30",
    name: "Magnesium Complex",
    priceCents: 2199,
    category: "supplements",
    image: "/images/bottles/magnesium.jpg",
    blurb: "The sacred mineral of calm. The bottle that reorders because people sleep.",
    description: "Magnesium is the sacred mineral of calm. This blend helps restore your nervous system, release tension, and rebalance the flow of your inner world.",
    benefits: ["Promotes muscle recovery and nerve function", "Supports restful sleep and emotional resilience", "Crucial for over 300 metabolic processes"],
    size: "30 capsules",
    servings: "30",
    bestseller: true,
    subscribeEligible: true,
    phase: 1,
    onHand: 24,
    rfqUnits: 96,
    cogsLow: 3.1,
    cogsHigh: 4.4,
    notes: "cGMP. Glycinate-forward. No oxide as the hero form. Replenish to 120.",
  },
  {
    slug: "vitamin-d",
    sku: "BL-D3-30",
    name: "Vitamin D3",
    priceCents: 1899,
    category: "supplements",
    image: "/images/bottles/vitamin-d.jpg",
    blurb: "Let the light in. Mood, immunity, bone — the winter staple.",
    description: "Let the light in. Vitamin D3 helps elevate your mood, immunity, and musculoskeletal strength — supporting vitality from the sun within.",
    benefits: ["Essential for bone and immune system strength", "Supports healthy calcium absorption", "May enhance mood and energy levels"],
    size: "30 capsules",
    servings: "30",
    bestseller: true,
    subscribeEligible: true,
    phase: 1,
    onHand: 25,
    rfqUnits: 95,
    cogsLow: 2.2,
    cogsHigh: 3.4,
    notes: "Cholecalciferol. Independent assay for IU. Replenish to 120.",
  },
  {
    slug: "vitamin-c-w-rose-hips",
    sku: "BL-VC-30",
    name: "Vitamin C with Rose Hips",
    priceCents: 1799,
    category: "supplements",
    image: "/images/bottles/vitamin-c.jpg",
    blurb: "The protector of your temple. Immune, skin, antioxidant.",
    description: "Vitamin C is the protector of your temple. Support your immune system, skin, and antioxidant defense with this clean and powerful classic.",
    benefits: ["Boosts immune function and resistance", "Promotes collagen for skin and joints", "Provides antioxidant support for stress recovery"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 18,
    rfqUnits: 82,
    cogsLow: 2.0,
    cogsHigh: 3.1,
    notes: "Rose hip on the panel. Replenish to 100.",
  },
  {
    slug: "vitamin-a",
    sku: "BL-VA-30",
    name: "Vitamin A",
    priceCents: 1699,
    category: "supplements",
    image: "/images/bottles/vitamin-a.jpg",
    blurb: "See the world more clearly. Completeness, not a trend.",
    description: "See the world more clearly. Vitamin A supports vision, immune integrity, and skin renewal — helping you stay connected, clear, and luminous.",
    benefits: ["Supports eye health and night vision", "Enhances immune function", "Aids in healthy skin cell production"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 18,
    rfqUnits: 42,
    cogsLow: 1.6,
    cogsHigh: 2.4,
    notes: "Thin inventory on purpose. Pregnancy warning on pack. Replenish to 60.",
  },
  {
    slug: "biotin",
    sku: "BL-BIO-30",
    name: "Biotin",
    priceCents: 1999,
    category: "supplements",
    image: "/images/bottles/biotin.jpg",
    blurb: "Beauty from the inside out. Hair, skin, nails — inner alignment, outer glow.",
    description: "Biotin helps your beauty radiate from the inside out. A vital B-vitamin that empowers your skin, hair, and nails — the outer glow of inner alignment.",
    benefits: ["Promotes strong hair and healthy nails", "Supports skin renewal and elasticity", "Helps convert nutrients into energy"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 24,
    rfqUnits: 76,
    cogsLow: 1.8,
    cogsHigh: 2.6,
    notes: "Search traffic SKU. Keep the formula boring and the brand beautiful.",
  },
  {
    slug: "collagen",
    sku: "BL-COL-30",
    name: "Marine Collagen",
    priceCents: 2499,
    category: "supplements",
    image: "/images/bottles/collagen.jpg",
    blurb: "Protein of regeneration. Skin, joints, bones — sourced with reverence from the sea.",
    description: "Our Marine Collagen nourishes the skin, joints, and bones — a protein of regeneration and resilience, sourced with reverence from the sea.",
    benefits: ["Supports healthy joints and skin elasticity", "Promotes collagen regeneration", "May reduce signs of aging and dryness"],
    size: "30 capsules",
    servings: "30",
    bestseller: true,
    subscribeEligible: true,
    phase: 1,
    onHand: 15,
    rfqUnits: 85,
    cogsLow: 6.5,
    cogsHigh: 9.0,
    notes: "Replenish first. Marine, not bovine.",
  },
  {
    slug: "womens-multi-vitamin-daily",
    sku: "BL-WMV-30",
    name: "Women's Multi-Vitamin Daily",
    priceCents: 2299,
    category: "supplements",
    image: "/images/bottles/womens-multi.jpg",
    blurb: "Divine rhythms of womanhood. Immunity, energy, hormonal balance — a daily ritual.",
    description: "At Blue Love, we honor the divine rhythms of womanhood with our Women's Multi-Vitamin. Each serving nurtures immunity, energy, and hormonal balance — an intentional ritual for thriving from within.",
    benefits: ["Supports daily energy and vitality", "Promotes immune balance and bone health", "Designed for the evolving needs of women"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 25,
    rfqUnits: 75,
    cogsLow: 4.2,
    cogsHigh: 6.0,
    notes: "Trust SKU. If this is junk, they will not buy NMN.",
  },
  {
    slug: "mens-multi-vitamin-daily",
    sku: "BL-MMV-30",
    name: "Men's Multi-Vitamin Daily",
    priceCents: 2299,
    category: "supplements",
    image: "/images/bottles/mens-multi.jpg",
    blurb: "Rooted in strength and clarity. Cells, mind, mission — every day.",
    description: "Rooted in strength and clarity, our Men's Multi-Vitamin supports foundational wellness for the masculine body. Empower your cells, mind, and mission — every single day.",
    benefits: ["Promotes immune strength and cardiovascular health", "Enhances energy metabolism and mental clarity", "Nourishment tailored to men's physiology"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 25,
    rfqUnits: 75,
    cogsLow: 4.0,
    cogsHigh: 5.8,
    notes: "Same bottle language as the women's. One house.",
  },
  {
    slug: "coq10",
    sku: "BL-COQ-30",
    name: "CoQ10",
    priceCents: 2999,
    category: "supplements",
    image: "/images/bottles/coq10.jpg",
    blurb: "The cellular spark. Heart, stamina, the energy that is already yours.",
    description: "CoQ10 is the cellular spark your body knows and remembers. Fuel your heart, enhance your stamina, and reclaim the energy that is innately yours.",
    benefits: ["Supports heart and cardiovascular function", "Enhances natural energy at the cellular level", "Aids in healthy aging and antioxidant protection"],
    size: "30 capsules",
    servings: "30",
    bestseller: true,
    subscribeEligible: true,
    phase: 1,
    onHand: 39,
    rfqUnits: 61,
    cogsLow: 5.5,
    cogsHigh: 8.0,
    notes: "Replenish to 100.",
  },
  {
    slug: "nmn",
    sku: "BL-NMN-30",
    name: "NMN",
    priceCents: 4499,
    category: "supplements",
    image: "/images/bottles/nmn.png",
    blurb: "500 mg. Not anti-aging. Pro-awakening. Margin lives here.",
    description: "Unlock cellular regeneration with NMN — the coenzyme precursor your body uses to restore vitality at the deepest level. This is not just anti-aging. This is pro-awakening. 500 mg. 30 capsules. 100% Love.",
    benefits: ["Supports NAD+ production and energy renewal", "Enhances mitochondrial function", "Promotes cognitive clarity and cellular repair"],
    size: "30 capsules",
    dose: "500 mg",
    servings: "30",
    bestseller: true,
    subscribeEligible: true,
    phase: 1,
    onHand: 20,
    rfqUnits: 80,
    cogsLow: 12.0,
    cogsHigh: 18.0,
    notes: "HPLC identity required. 500 mg on the actual label. Replenish to 100.",
  },
  {
    slug: "nac",
    sku: "BL-NAC-30",
    name: "NAC",
    priceCents: 2499,
    category: "supplements",
    image: "/images/bottles/nac.jpg",
    blurb: "Glutathione. Liver. A path to purification — guided by nature.",
    description: "Our NAC formula invites balance from within, boosting your natural antioxidant defense and gently supporting liver health. It's a path to purification — lovingly guided by nature.",
    benefits: ["Boosts glutathione, your master antioxidant", "Supports respiratory and liver function", "Aids in detox and immune regulation"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 24,
    rfqUnits: 76,
    cogsLow: 3.8,
    cogsHigh: 5.5,
    notes: "Replenish to 100.",
  },
  {
    slug: "energy-booster-caffeine",
    sku: "BL-EN-30",
    name: "Energy Booster",
    priceCents: 2199,
    category: "supplements",
    image: "/images/bottles/energy.jpg",
    blurb: "Awakens potential without the crash. Clarity, movement, momentum.",
    description: "Our Energy Booster capsule awakens your potential without the crash. Designed for clarity, movement, and momentum — aligned with your purpose.",
    benefits: ["Supports mental focus and alertness", "Helps increase physical performance", "Clean stimulation without overstimulation"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 25,
    rfqUnits: 75,
    cogsLow: 2.8,
    cogsHigh: 4.2,
    notes: "Caffeine disclosed on the panel. Replenish to 100.",
  },
  {
    slug: "fisetin",
    sku: "BL-FIS-30",
    name: "Fisetin",
    priceCents: 3299,
    category: "supplements",
    image: "/images/bottles/fisetin.jpg",
    blurb: "Botanical intelligence. Cellular waste, brain clarity, aging consciously.",
    description: "Fisetin is a botanical intelligence known for clearing cellular waste and promoting brain clarity. A plant-based ally in the art of aging consciously.",
    benefits: ["Encourages senolytic activity (removes aging cells)", "Supports brain performance and memory", "Protects against oxidative stress", "Helps reduce inflammation and oxidative damage"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 15,
    rfqUnits: 45,
    cogsLow: 7.5,
    cogsHigh: 11.0,
    notes: "Tied with collagen for thinnest count. Replenish to 60 — not 200.",
  },
  {
    slug: "resveratrol",
    sku: "BL-RES-30",
    name: "Resveratrol",
    priceCents: 2999,
    category: "supplements",
    image: "/images/bottles/resveratrol.jpg",
    blurb: "99.9% purity. Inner longevity. Clarity, vitality, cardiovascular strength.",
    description: "Blue Love's Resveratrol is a botanical force for inner longevity. Sourced at 99.9% purity and crafted without unnecessary fillers, this potent antioxidant invites clarity, vitality, and cardiovascular strength into your daily ritual.",
    benefits: ["Antioxidant defense — protects cells from oxidative stress", "Cognitive clarity — healthy blood flow and neural protection", "Heart harmony — vascular health and circulation", "Liver support — metabolic balance and detox"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 20,
    rfqUnits: 40,
    cogsLow: 6.0,
    cogsHigh: 9.0,
    notes: "Purity claim needs a COA. Replenish to 60.",
  },
  {
    slug: "lions-mane-mushroom-extract",
    sku: "BL-LM-30",
    name: "Lion's Mane Mushroom Extract",
    priceCents: 2799,
    category: "supplements",
    image: "/images/bottles/lions-mane.jpg",
    blurb: "Mushroom of memory and spirit. Mind and soul, reconnected.",
    description: "Lion's Mane is a mushroom of memory and spirit. Revered in traditional medicine, it supports brain clarity and the reconnection of mind and soul.",
    benefits: ["Promotes neurogenesis and cognitive sharpness", "Supports nerve regeneration", "Encourages balanced mood and creativity"],
    size: "30 capsules",
    servings: "30",
    bestseller: true,
    subscribeEligible: true,
    phase: 1,
    onHand: 30,
    rfqUnits: 90,
    cogsLow: 4.5,
    cogsHigh: 6.8,
    notes: "Strongest mushroom count. Replenish to 120.",
  },
  {
    slug: "cordyceps-mushroom-extract",
    sku: "BL-COR-30",
    name: "Cordyceps Mushroom Extract",
    priceCents: 2799,
    category: "supplements",
    image: "/images/bottles/cordyceps.jpg",
    blurb: "Sustained energy, cellular clarity, flow. 99.9% pure. Vegan.",
    description: "Cordyceps is nature's invitation to sustained energy, cellular clarity, and flow. Revered in Eastern medicine and now backed by modern wellness, our high-potency Cordyceps extract helps awaken your vitality, fortify your immune system, and support deep endurance. This vegan formula is 99.9% pure, free of fillers, and offered in gratitude to your body's natural intelligence.",
    benefits: ["Natural antioxidant power — long-term vitality", "Heart flow support — circulation", "Skin radiance through antioxidant activity", "Endurance and recovery for active lives"],
    size: "30 capsules",
    servings: "30",
    subscribeEligible: true,
    phase: 1,
    onHand: 20,
    rfqUnits: 80,
    cogsLow: 4.8,
    cogsHigh: 7.2,
    notes: "Replenish to 100.",
  },
{
    slug: "house-incense",
    sku: "BL-INC-20",
    name: "House Incense",
    priceCents: 1600,
    category: "aromatics",
    image: "/images/sundry/incense.jpg",
    blurb: "Highest turn in the sundry aisle. Copal and a quiet wood. People finish boxes.",
    description:
      "Metaphysical retailers put incense at the top of 2026 bestseller lists because it is cheap, photogenic, and consumed. Twenty sticks. One house blend — copal, a little citrus, a little wood. Not nag champa in a Blue Love box. If it does not smell like this house, do not print the mark on it.",
    benefits: ["Daily ritual", "Repeat purchase", "Cart add-on under $20"],
    size: "20 sticks",
    phase: 2,
    onHand: 0,
    rfqUnits: 240,
    cogsLow: 1.4,
    cogsHigh: 2.6,
    notes:
      "VELOCITY A. Wholesale incense packs run $0.80–2.50. Retail $12–18. 70%+ margin. First sundry PO. Natural sticks, no synthetic perfume bomb.",
  },
  {
    slug: "smudge-kit",
    sku: "BL-SMU-1",
    name: "Smudge Kit",
    priceCents: 3200,
    category: "aromatics",
    image: "/images/sundry/smudge-kit.jpg",
    blurb: "The gift SKU. Sage, wood, dish, matches, one rose quartz point. Ships as a complete ritual.",
    description:
      "The kit that shows up in every Etsy and Amazon bestseller screenshot because it is a gift, not a commodity stick. Cultivated garden sage — not wild-harvest California white sage. Palo santo only if the vendor has a deadfall / farm letter; otherwise copal resin rides in the kit. Navy dish. Long matches. One small rose quartz. This is how a $45 supplement order becomes $75.",
    benefits: ["Clears a room", "Gifts without thinking", "Raises AOV"],
    size: "Kit",
    phase: 2,
    onHand: 0,
    rfqUnits: 120,
    cogsLow: 7.5,
    cogsHigh: 11.0,
    notes:
      "VELOCITY A. Generic Amazon kits $9–15. Branded $28–38. Do not buy wild white sage. First Nations and overharvest are real. Cultivated sage or cedar/rosemary. Palo santo: deadfall only, or skip for copal.",
  },
  {
    slug: "cultivated-sage",
    sku: "BL-SAGE-1",
    name: "Cultivated Sage Bundle",
    priceCents: 1400,
    category: "aromatics",
    image: "/images/sundry/smudge-kit.jpg",
    blurb: "Refill for the kit. Grown, not stripped from Chumash land.",
    description:
      "Single 4-inch cultivated sage bundle. The refill SKU next to the kit. Wholesale cultivated bundles run about $1.70–2.10. Wild white sage is a brand risk — skip it even if it is cheaper.",
    benefits: ["Refill", "Impulse under $15"],
    size: "1 bundle",
    phase: 2,
    onHand: 0,
    rfqUnits: 120,
    cogsLow: 1.7,
    cogsHigh: 2.4,
    notes: "VELOCITY A. Third Eye Sage and Faire are typical vendors. Demand a grower name.",
  },
  {
    slug: "copal-resin",
    sku: "BL-COP-1",
    name: "Copal Resin",
    priceCents: 1800,
    category: "aromatics",
    image: "/images/sundry/incense.jpg",
    blurb: "The honest substitute when palo santo papers are weak.",
    description:
      "Copal is the Mesoamerican resin that actually burns as a ritual, not a Pinterest stick. Use it in the kit if palo santo provenance fails. Small glass jar. Charcoal disc in the box.",
    benefits: ["Smoke without the CITES problem", "Pairs with the dish"],
    size: "1 oz jar",
    phase: 2,
    onHand: 0,
    rfqUnits: 80,
    cogsLow: 2.8,
    cogsHigh: 4.5,
    notes: "VELOCITY B. Buy with the dish. Include two charcoal discs.",
  },
  {
    slug: "infinity-candle",
    sku: "BL-CND-8",
    name: "Infinity Candle",
    priceCents: 3200,
    category: "aromatics",
    image: "/images/candle.jpg",
    blurb: "Soy, navy glass, one scent. The house on a wick.",
    description:
      "Scented soy candles wholesale at $4–14 and retail $20–42 with 50–70% margin. One scent. Do not launch a flight of five. Cotton wick, phthalate-free. Navy vessel with the infinity. This is the object people photograph.",
    benefits: ["Gift", "Atmosphere", "Brand in the room"],
    size: "8 oz",
    phase: 2,
    onHand: 0,
    rfqUnits: 150,
    cogsLow: 6.0,
    cogsHigh: 12.0,
    notes:
      "VELOCITY A. Custom branded vessel is the point — generic white soy is Amazon's game. MOQ often 100–200 for a printed glass.",
  },
  {
    slug: "aura-mist",
    sku: "BL-MST-1",
    name: "Aura Mist",
    priceCents: 2400,
    category: "aromatics",
    image: "/images/mist.jpg",
    blurb: "Smoke-free rooms. Lavender, frankincense, a little salt.",
    description:
      "Not everyone can burn. A 2 oz room/aura mist is the smoke-free sister of the kit. Essential oil roller/mist COGS $3–8, retail $18–28. Keep the formula short and the label honest.",
    benefits: ["Apartments", "Travel", "No open flame"],
    size: "2 oz",
    phase: 2,
    onHand: 0,
    rfqUnits: 80,
    cogsLow: 3.5,
    cogsHigh: 7.0,
    notes: "VELOCITY B. Glass, not plastic. No 'legal to claim it clears entities.'",
  },
  {
    slug: "ritual-matches",
    sku: "BL-MAT-1",
    name: "Infinity Matches",
    priceCents: 1200,
    category: "aromatics",
    image: "/images/sundry/matches.jpg",
    blurb: "Extra-long matches in a navy tin. The cheapest branded object that still feels like a gift.",
    description:
      "Cart add-on. COGS $1.50–3. Retail $10–14. Sits next to the candle and the kit. People buy it because it is small and finished.",
    benefits: ["Add-on", "Gift with the candle"],
    size: "Tin",
    phase: 2,
    onHand: 0,
    rfqUnits: 200,
    cogsLow: 1.5,
    cogsHigh: 3.0,
    notes: "VELOCITY A. Extra-long only. Short matches look like a gas station.",
  },
  {
    slug: "five-stone-starter",
    sku: "BL-STN-5",
    name: "Five Stone Starter",
    priceCents: 3800,
    category: "stones",
    image: "/images/sundry/starter-kit.jpg",
    blurb: "Rose quartz, amethyst, clear quartz, selenite, black tourmaline. The only crystal SKU you need at launch.",
    description:
      "2025 bulk crystal lists collapse to the same five: amethyst, rose quartz, citrine, fluorite, clear quartz. We swap citrine/fluorite for selenite (cleanse) and black tourmaline (ground) because this house is love + practice, not a prosperity mall. Tumbled, pouch, one card. Do not stock 40 SKUs of leopard jasper.",
    benefits: ["Gift", "Beginner", "Instagram without looking like a mall"],
    size: "5 tumbled + pouch",
    phase: 2,
    onHand: 0,
    rfqUnits: 100,
    cogsLow: 5.0,
    cogsHigh: 9.0,
    notes:
      "VELOCITY A. Towers and hearts have the highest markup; tumbled kits have the highest turns. No aura coating, no dyed howlite sold as turquoise. Ask for origin.",
  },
  {
    slug: "rose-quartz-heart",
    sku: "BL-RQ-H",
    name: "Rose Quartz Heart",
    priceCents: 2200,
    category: "stones",
    image: "/images/sundry/rose-heart.jpg",
    blurb: "The love stone. Valentine, mother, 'just because.' This is the Blue Love crystal.",
    description:
      "Rose quartz hearts are the Etsy holiday machine. Wholesale hearts by the kilo. Retail $16–28 for a palm stone. One size, polished, not a 12-SKU heart wall.",
    benefits: ["Gift", "On-brand", "Pairs with the necklace"],
    size: "Palm",
    phase: 2,
    onHand: 0,
    rfqUnits: 80,
    cogsLow: 2.5,
    cogsHigh: 6.0,
    notes: "VELOCITY A. Pink/white packaging. This is the stone that belongs on this site.",
  },
  {
    sku: "BL-SEL-W",
    slug: "selenite-wand",
    name: "Selenite Wand",
    priceCents: 1800,
    category: "stones",
    image: "/images/sundry/selenite.jpg",
    blurb: "The cleanser. Sits next to the kit. People understand it in one sentence.",
    description:
      "Selenite wands are in every beginner kit on Etsy because the story is simple: it clears the other stones. Satin spar, 6–8 inches. Fragile — pack like glass.",
    benefits: ["Cleanses the other stones", "Altar"],
    size: "6–8 in",
    phase: 2,
    onHand: 0,
    rfqUnits: 80,
    cogsLow: 2.0,
    cogsHigh: 5.0,
    notes: "VELOCITY B. Breakage allowance 8%. Morocco satin spar is the common grade.",
  },
  {
    slug: "infinity-necklace",
    sku: "BL-JW-INF",
    name: "Infinity Necklace",
    priceCents: 7800,
    category: "stones",
    image: "/images/sundry/infinity-necklace.jpg",
    blurb: "The mark on a chain. Gold-fill, not costume plate that turns green.",
    description:
      "Fashion jewelry conversion sits around 1.5–3% with AOV $40–85 for fashion, higher for fine. This is the brand jewel — a small infinity in gold-fill on an 18-inch chain. If you cannot afford gold-fill, do sterling. Do not do $8 Amazon plate with the logo on it.",
    benefits: ["Wear the house", "Gift", "Highest sundry ticket"],
    size: "18 in",
    phase: 2,
    onHand: 0,
    rfqUnits: 60,
    cogsLow: 14,
    cogsHigh: 28,
    notes:
      "VELOCITY B. Test 60 units. If they sit, do not reorder. If they move, this is the $78 hero that lifts AOV next to a $22 magnesium.",
  },
  {
    slug: "rose-quartz-mala",
    sku: "BL-JW-MALA",
    name: "Rose Quartz Mala",
    priceCents: 5800,
    category: "stones",
    image: "/images/sundry/mala.jpg",
    blurb: "108 beads. For the sitting, not for the festival.",
    description:
      "108-bead 8mm rose quartz malas wholesale $8–18, Amazon races them at $20, real shops sell $48–98. Hand-knotted, navy tassel, guru bead. If it is strung on elastic with no knots, it is a bracelet pretending.",
    benefits: ["Practice object", "Pairs with Be Love"],
    size: "108 × 8 mm",
    phase: 2,
    onHand: 0,
    rfqUnits: 50,
    cogsLow: 9,
    cogsHigh: 18,
    notes: "VELOCITY B. Buy hand-knotted. Count the beads. Photograph on the companion.",
  },
  {
    slug: "amethyst-bracelet",
    sku: "BL-JW-BR",
    name: "Amethyst Bracelet",
    priceCents: 2800,
    category: "stones",
    image: "/images/sundry/starter-kit.jpg",
    blurb: "Stretch, 8 mm, the impulse jewel. Calm on a wrist.",
    description:
      "Beaded stretch bracelets are the jewelry impulse SKU. COGS $3–8. Retail $22–32. Amethyst because it is the other stone people already know. One size with a 7-inch plus three 6.5 and three 7.5 in the case.",
    benefits: ["Impulse", "Stacks", "Under $30"],
    size: "7 in stretch",
    phase: 2,
    onHand: 0,
    rfqUnits: 80,
    cogsLow: 3.5,
    cogsHigh: 8.0,
    notes: "VELOCITY A. Elastic that does not snap in a week. Natural amethyst, not glass.",
  },
  {
    slug: "sacred-infinity-tee",
    sku: "BL-TEE-UN",
    name: "Sacred Infinity Tee",
    priceCents: 3400,
    category: "apparel",
    image: "/images/tee.jpg",
    blurb: "The only apparel to print first. Volume. Size mix 2/4/4/2.",
    description:
      "Apparel conversion is the worst in ecommerce (about 2.9–3.3%). Health/wellbeing converts better than clothes — so the tee is a billboard, not the P&L. Soft cotton. Infinity small at the chest. Do not print a paragraph. Size run S24 M36 L24 XL12.",
    benefits: ["Billboard", "Community"],
    size: "S–XL",
    phase: 2,
    onHand: 0,
    rfqUnits: 96,
    cogsLow: 7,
    cogsHigh: 11,
    notes: "VELOCITY B. Test before the hoodie. Heavyweight 200+ gsm so it does not feel like a 5K shirt.",
  },
  {
    slug: "infinity-cap",
    sku: "BL-CAP-1",
    name: "Infinity Cap",
    priceCents: 3200,
    category: "apparel",
    image: "/images/cap.jpg",
    blurb: "One size. No size curve. The safest apparel SKU.",
    description:
      "Embroidered dad cap, navy, small infinity. Embroidered caps wholesale $8–14. Retail $28–38. No size risk. People actually wear hats.",
    benefits: ["No size curve", "Wear the mark"],
    size: "One size",
    phase: 2,
    onHand: 0,
    rfqUnits: 72,
    cogsLow: 8,
    cogsHigh: 14,
    notes: "VELOCITY A among apparel. Embroider, do not print.",
  },
  {
    slug: "infinity-tote",
    sku: "BL-TOTE-1",
    name: "Infinity Tote",
    priceCents: 2200,
    category: "apparel",
    image: "/images/sundry/tote.jpg",
    blurb: "The AOV add-on. Canvas, small mark, ships flat.",
    description:
      "Printed canvas tote COGS $4–8, retail $18–24. Ships in the same box as the bottles. The cheapest way to get the infinity into a grocery store.",
    benefits: ["Add-on", "Ships flat"],
    size: "Canvas",
    phase: 2,
    onHand: 0,
    rfqUnits: 80,
    cogsLow: 4,
    cogsHigh: 8,
    notes: "VELOCITY A. Heavy canvas so it does not look like a conference freebie.",
  },
  {
    slug: "love-is-the-answer-hoodie",
    sku: "BL-HD-UN",
    name: "Love Is the Answer Hoodie",
    priceCents: 6800,
    category: "apparel",
    image: "/images/hoodie.jpg",
    blurb: "Print after the tee moves. Size mix is the risk.",
    description:
      "French terry, unisex, infinity at the heart. Hoodies eat cash in leftover XL. Cut this check only after the tee size mix is real. 48 units, not 96.",
    benefits: ["Margin", "Winter"],
    size: "S–XL",
    phase: 2,
    onHand: 0,
    rfqUnits: 48,
    cogsLow: 18,
    cogsHigh: 26,
    notes: "VELOCITY C. Do not lead with this. Size 8/16/16/8.",
  },
  {
    slug: "the-practice-journal",
    sku: "BL-JRN-1",
    name: "The Practice Journal",
    priceCents: 2400,
    category: "books-audio",
    image: "/images/journal.jpg",
    blurb: "House paper. 40 days. One sitting, one line. Not Tolle — you do not own Tolle.",
    description:
      "Guided journals are what actually sell in the New Age aisle on Amazon, not another copy of The Power of Now. You will lose that fight to Amazon. Print a house journal that pairs with the Foundation Series. POD until 80 sell, then a 200 offset.",
    benefits: ["Pairs with Be Love", "You own the IP"],
    size: "Notebook",
    phase: 2,
    onHand: 0,
    rfqUnits: 80,
    cogsLow: 3.2,
    cogsHigh: 6.0,
    notes:
      "VELOCITY B. Do not buy Eckhart Tolle, Michael Singer, or Gabby Bernstein to resell. Amazon owns that. House IP only.",
  },
  {
    slug: "thirty-day-cards",
    sku: "BL-CRD-30",
    name: "Thirty-Day Card Deck",
    priceCents: 1800,
    category: "books-audio",
    image: "/images/sundry/cards.jpg",
    blurb: "The Foundation Series in the hand. One card, one day. The cheapest way to ship the companion.",
    description:
      "Affirmation and oracle decks turn because they are gifts. Print the 30 Foundation titles, affirmations, and the infinity. Tuck box. This is merch that is also the product.",
    benefits: ["Gift", "Practice object", "You own the words"],
    size: "30 cards",
    phase: 2,
    onHand: 0,
    rfqUnits: 150,
    cogsLow: 3.0,
    cogsHigh: 7.0,
    notes: "VELOCITY A. Print in the US or a deck printer with a 100–250 MOQ. Use the library copy you already wrote.",
  },
  {
    slug: "6-week-digital-course",
    sku: "BL-CRS-1",
    name: "6-Week Digital Course",
    priceCents: 5500,
    category: "digital",
    image: "/images/digital.jpg",
    blurb: "Find / Share / Be as a curriculum. Not built yet — do not sell a ghost.",
    description:
      "Listed so the RFQ carries a production budget. Unlock when the lessons exist.",
    benefits: ["Practice, structured"],
    size: "Digital",
    digital: true,
    phase: 2,
    onHand: 0,
    rfqUnits: 1,
    cogsLow: 0,
    cogsHigh: 4500,
    notes: "Production budget, not a PO line. Do not take money until the files exist.",
  },
];

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function inStock(p: Product) {
  return p.onHand > 0 && !p.digital;
}

export function byCategory(id: Category) {
  return PRODUCTS.filter((p) => p.category === id);
}

export function money(cents: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(
    cents / 100,
  );
}

export const CIRCULATION_RATE = 0.03;
export const FIRST_ORDER_RATE = 0.3;
export const SUBSCRIBE_RATE = 0.15;
export const ON_HAND_TOTAL = PRODUCTS.reduce((n, p) => n + p.onHand, 0);

export function unitCents(
  product: Product,
  opts: { subscribe?: boolean; firstOrder?: boolean; tier?: string | null } = {},
) {
  let cents = product.priceCents;
  if (opts.subscribe && product.subscribeEligible) {
    cents = Math.round(cents * (1 - SUBSCRIBE_RATE));
  }
  const member =
    opts.tier === "seeker" ? 0.1 : opts.tier === "circle" ? 0.18 : opts.tier === "devotee" ? 0.25 : 0;
  const disc = Math.max(opts.firstOrder ? FIRST_ORDER_RATE : 0, member);
  return Math.round(cents * (1 - disc));
}

export const SKIP_SUNDRY: { name: string; reason: string }[] = [
  {
    name: "Wild California white sage",
    reason: "Overharvest plus cultural theft. Cultivated sage or cedar/rosemary instead.",
  },
  {
    name: "Green palo santo / living-tree cuts",
    reason: "Slow-growing, watch-listed. Deadfall with a farm letter, or copal resin.",
  },
  {
    name: "40-SKU crystal mall",
    reason: "Amethyst, rose quartz, clear quartz, selenite, black tourmaline. That is the list. Aura coating and dyed howlite destroy trust.",
  },
  {
    name: "Costume-plate jewelry",
    reason: "Turns green, tanks reviews. Gold-fill or sterling or skip the necklace.",
  },
  {
    name: "Tibetan singing bowls",
    reason: "Amazon race to $18. Freight is brutal. Skip until AOV needs a $45 object.",
  },
  {
    name: "Licensed books (Tolle, Singer, Bernstein, Coelho)",
    reason: "Amazon owns that aisle. House journal and the 30-day deck are the paper you can own.",
  },
  {
    name: "Yoga bolsters, cushions, mats",
    reason: "Cube shipping. Skip.",
  },
  {
    name: "Five candle scents",
    reason: "One scent. The rest become dead stock.",
  },
];
