export type LibraryDay = {
  day: number;
  title: string;
  theme: string;
  minutes: number;
  meditation: string;
  affirmation: string;
  prompt: string;
};

export const LIBRARY: LibraryDay[] = [
  {
    day: 1,
    title: "Welcome to Intentional Living",
    theme: "Beginning the Journey",
    minutes: 7,
    meditation: "Welcome, beautiful soul. Today marks the first day of your intentional living practice. Take a deep breath and feel the infinite potential within you. You are not here by accident\u2014your presence in this moment is a manifestation of your soul's desire for growth, peace, and authentic connection.\n\nClose your eyes and imagine a brilliant blue light surrounding your body, pulsing with unconditional love. This light represents your highest self, the version of you that already embodies all the wisdom, compassion, and strength you seek. With each breath, this light grows brighter, filling every cell of your being.\n\nToday, set the intention to notice love in unexpected places. It might appear as a stranger's smile, the warmth of sunlight on your skin, or the comfort of your morning coffee. Love is everywhere, waiting for you to recognize it.",
    affirmation: "I am worthy of love, and I choose to see love in all things.",
    prompt: "What brought you to this meditation practice today? What do you hope to cultivate in your life?",
  },
  {
    day: 2,
    title: "The Power of Breath",
    theme: "Foundational Practice",
    minutes: 7,
    meditation: "Your breath is the bridge between your conscious mind and your infinite soul. In this moment, bring all of your attention to your breathing. Notice the cool air entering your nostrils, filling your lungs, and the warm air leaving your body.\n\nAs you breathe in, silently say \"I am.\" As you breathe out, say \"at peace.\" Continue this rhythm: \"I am\" (inhale), \"at peace\" (exhale). If your mind wanders\u2014and it will\u2014gently guide it back to your breath without judgment.\n\nYour breath is always with you, a constant companion and anchor in stormy seas. When life feels overwhelming, return to this simple practice. Three conscious breaths can shift your entire energy field.",
    affirmation: "My breath connects me to the universal flow of life.",
    prompt: "When do you most need to pause and breathe? How can you remember to use this tool throughout your day?",
  },
  {
    day: 3,
    title: "Gratitude as Gateway",
    theme: "Appreciation Practice",
    minutes: 7,
    meditation: "Gratitude is the fastest path to joy. Today, we practice appreciation not for what we hope to receive, but for what already exists in our lives. Begin by placing your hand over your heart. Feel its steady, faithful rhythm\u2014this heart that has beaten for you every moment of your life without asking for recognition.\n\nThank your heart. Thank your body for carrying you through this world. Now, expand outward. Think of three people who have touched your life positively. See their faces in your mind's eye and send them waves of gratitude. They may never know you're thinking of them, but your appreciation ripples through the universe.\n\nFinally, express gratitude for the challenges that have shaped you. Every obstacle has been a teacher, every setback a redirection toward your highest path.",
    affirmation: "I am abundant in blessings, and I recognize them with gratitude.",
    prompt: "List 10 things you're grateful for today. Include at least three that you usually take for granted.",
  },
  {
    day: 4,
    title: "Releasing What No Longer Serves",
    theme: "Letting Go",
    minutes: 7,
    meditation: "Imagine yourself standing at the edge of a gentle river under a star-filled sky. In your hands, you hold a basket filled with heavy stones. Each stone represents something you've been carrying that no longer serves your highest good\u2014old grudges, limiting beliefs, fears, regrets.\n\nOne by one, take each stone and examine it. What does it represent? Thank it for any lessons it brought you, then release it into the flowing river. Watch as the current carries it away, dissolving it into stardust.\n\nWith each stone you release, you feel lighter. Your shoulders drop, your breath deepens, your spirit soars. You are not meant to carry these burdens. Release them with love, creating space for new blessings to enter your life.",
    affirmation: "I release what no longer serves me and welcome new possibilities.",
    prompt: "What are you ready to let go of? Write it down, then (if you feel called) tear up the paper as a symbolic release.",
  },
  {
    day: 5,
    title: "Self-Compassion Practice",
    theme: "Inner Kindness",
    minutes: 7,
    meditation: "Place both hands on your chest and feel the warmth radiating from your palms. This is your own loving energy, always available to comfort and support you. Today, we practice speaking to ourselves as we would to our most beloved friend.\n\nThink of a recent moment when you were hard on yourself\u2014a mistake you made, a goal you didn't reach, a way you felt you fell short. Now, imagine a cherished friend came to you with this same struggle. What would you say to them? How would your voice sound\u2014gentle, understanding, supportive?\n\nOffer yourself these same words. You deserve the compassion you so freely give to others. You are doing your best with the awareness you have in each moment. That is enough. You are enough.",
    affirmation: "I treat myself with the same love and kindness I offer to others.",
    prompt: "Write a compassionate letter to yourself from your highest, wisest self. What does that version of you want you to know?",
  },
  {
    day: 6,
    title: "Heart-Opening Meditation",
    theme: "Emotional Connection",
    minutes: 7,
    meditation: "Visualize a small, glowing orb of emerald light in the center of your chest\u2014this is your heart chakra, your center of love and connection. As you breathe, this light grows brighter and larger with each inhale, filling your entire chest cavity.\n\nAllow any emotions to arise without judgment. Your heart may feel tender, raw, guarded, or wide open. All of these states are valid. Breathe into whatever you discover there. As the green light expands, it gently melts any walls you've built around your heart for protection.\n\nThese walls once served you, but perhaps now they're keeping out the very connection you crave. With each breath, the light grows, extending beyond your body, creating an energetic field of unconditional love around you. From this open-hearted space, you magnetize authentic, loving connections.",
    affirmation: "My heart is safe to open. I give and receive love freely.",
    prompt: "Where do you notice walls around your heart? What would it feel like to let them down, even slightly?",
  },
  {
    day: 7,
    title: "Finding Your Center",
    theme: "Inner Stability",
    minutes: 7,
    meditation: "Imagine a golden thread running from the crown of your head down through your spine, through your body, and deep into the Earth's core. This is your axis, your center, your unshakeable foundation.\n\nNo matter what storms rage around you\u2014external chaos, others' emotions, your own swirling thoughts\u2014this golden thread remains steady. You can always return to this center. Feel its strength, its permanence, its peace.\n\nWhen you operate from this centered place, you respond to life rather than react to it. You make decisions from clarity rather than fear. You move through the world with grounded confidence. This center is always accessible. One breath, one moment of awareness, and you're home.",
    affirmation: "I am centered, grounded, and at peace within myself.",
    prompt: "What throws you off center? How can you practice returning to your center more quickly?",
  },
  {
    day: 8,
    title: "The Power of Presence",
    theme: "Mindfulness",
    minutes: 7,
    meditation: "This moment\u2014right now\u2014is all that truly exists. The past is a memory, the future a projection. Only now is real, and in this now, you have everything you need.\n\nBring your full attention to your immediate sensory experience. What do you hear? Perhaps the hum of distant traffic, birds singing, your own breath. What do you feel? The temperature of air on your skin, the support of the ground beneath you, the weight of your body.\n\nNotice how when you're fully present, worry dissolves. Anxiety cannot exist in this moment\u2014only in thoughts about the future. Regret cannot exist here\u2014only in thoughts about the past. Right now, in this breath, you are safe. You are whole. You are enough.",
    affirmation: "I am fully present in this moment, and this moment is perfect.",
    prompt: "What pulls you out of the present moment most often? How can you gently guide yourself back?",
  },
  {
    day: 9,
    title: "Abundance Consciousness",
    theme: "Prosperity Mindset",
    minutes: 7,
    meditation: "Look around your life and notice all the abundance already present. You have air to breathe\u2014unlimited, free, always available. You have this body, this miraculous organism that performs millions of functions without your conscious thought. You have access to this meditation, this moment of peace.\n\nAbundance is not just money\u2014it's love, time, friendship, beauty, opportunity, ideas, energy. Where you place your attention grows. If you focus on lack, you'll find evidence of lack. If you focus on abundance, you'll discover it everywhere.\n\nFeel the sensation of abundance in your body. It feels like expansion, possibility, joy, trust. From this energy, you become a magnet for more blessings. Opportunities flow to you because you're open to receiving them.",
    affirmation: "I am abundant in all ways. The universe provides for me generously.",
    prompt: "Where do you already have abundance in your life that you haven't been acknowledging?",
  },
  {
    day: 10,
    title: "Emotional Awareness",
    theme: "Feeling Your Feelings",
    minutes: 8,
    meditation: "Emotions are energy in motion\u2014they want to flow through you, not get stuck in you. Today, we practice welcoming all emotions as messengers, each carrying important information.\n\nScan your body for any emotional sensations. Perhaps tightness in your chest, a knot in your stomach, warmth in your face, lightness in your shoulders. Don't try to change these sensations\u2014simply acknowledge them.\n\nIf you can identify the emotion, name it: \"This is sadness.\" \"This is excitement.\" \"This is fear.\" Naming emotions reduces their power over you. Now breathe into the sensation, giving it permission to be there. Tell it: \"I see you. I accept you. What do you need me to know?\"\n\nEmotions pass more quickly when we allow them rather than resist them. You are not your emotions\u2014you are the observer of emotions, the sky that remains unchanged while weather patterns move through.",
    affirmation: "All of my emotions are welcome. I am safe to feel what I feel.",
    prompt: "What emotion are you feeling right now? Where do you feel it in your body? What might it be trying to tell you?",
  },
  {
    day: 11,
    title: "Forgiving Yourself",
    theme: "Self-Forgiveness",
    minutes: 8,
    meditation: "Bring to mind something you've been holding against yourself\u2014a mistake, a regret, a moment you wish you could redo. Now, see yourself in that moment through the eyes of compassion.\n\nYou were doing the best you could with the awareness, tools, and emotional resources you had at that time. You didn't know what you know now. You didn't have the perspective you have now. And even if you \"should have known better,\" you're human. Humans make mistakes. That's how we learn and grow.\n\nPlace your hand on your heart and say: \"I forgive you. I forgive you for not being perfect. I forgive you for being human. I forgive you, and I release you.\" Feel the weight of self-judgment dissolving, creating space for peace and self-acceptance.",
    affirmation: "I forgive myself completely and move forward with wisdom and grace.",
    prompt: "Write yourself a forgiveness letter. Be specific about what you're forgiving yourself for and why.",
  },
  {
    day: 12,
    title: "Connecting to Your Body",
    theme: "Embodiment",
    minutes: 8,
    meditation: "Your body is not just a vessel\u2014it's your home, your temple, your sacred space in this physical world. Today, we honor it with loving attention.\n\nStarting at the top of your head, mentally scan down through your body. Notice each area without judgment: your scalp, forehead, eyes, jaw, neck, shoulders, arms, chest, belly, hips, legs, feet. Thank each part for its service.\n\nYour body has carried you through every experience of your life. It has worked tirelessly to keep you alive and healthy. It has generated energy when you asked, rested when you allowed, healed injuries, fought off illness, and adapted to countless circumstances.\n\nSend waves of appreciation through every cell. Commit to treating your body with respect, nourishing it with good food, movement, rest, and kind words.",
    affirmation: "My body is a miracle, and I honor it with love and care.",
    prompt: "What is your relationship with your body? How can you show it more appreciation?",
  },
  {
    day: 13,
    title: "The Art of Receiving",
    theme: "Opening to Receive",
    minutes: 8,
    meditation: "Many of us have learned to give generously but struggle to receive. Today, we practice opening to life's gifts. Place your hands palm-up in your lap, a universal gesture of receptivity.\n\nImagine a golden light pouring down from the cosmos, filling your cupped hands, overflowing into your lap, surrounding your entire body. This is the universe's abundance, always flowing, always available. The question is: are you open to receive it?\n\nNotice any resistance that arises. Do you feel you don't deserve it? That you must earn it first? That receiving makes you weak or indebted? These are just thoughts, not truths. You deserve good things simply because you exist.\n\nPractice saying \"thank you\" without deflecting or minimizing. Practice accepting compliments, help, gifts, and opportunities with grace. The more you receive, the more you have to give. You cannot pour from an empty cup.",
    affirmation: "I am worthy of receiving love, abundance, and support. I accept with gratitude.",
    prompt: "When someone offers you something (help, a compliment, a gift), what's your automatic response? How can you practice receiving more gracefully?",
  },
  {
    day: 14,
    title: "Finding Joy in the Ordinary",
    theme: "Everyday Magic",
    minutes: 8,
    meditation: "Life's greatest pleasures are often hidden in plain sight, waiting for us to slow down enough to notice them. Today, we practice presence through appreciation of simple things.\n\nThink about your morning coffee or tea. Before you took your first sip, you might have rushed through preparing it, thinking about your to-do list. But consider: someone grew these beans or leaves, someone harvested them, someone transported them, someone roasted or processed them, someone sold them, and you prepared them. Hundreds of people and natural forces collaborated so you could enjoy this simple pleasure.\n\nEverything in your life is like this\u2014a miracle of interconnection. The sunset, the warm water in your shower, the clothes on your body, the technology allowing you to access this meditation. When you pause to truly see the ordinary, it becomes extraordinary.",
    affirmation: "I find magic and joy in the simple, everyday moments of my life.",
    prompt: "What ordinary thing brought you unexpected joy recently? How can you build more awareness of these moments?",
  },
  {
    day: 15,
    title: "Courage to Be Authentic",
    theme: "True Self Expression",
    minutes: 8,
    meditation: "There is a version of you that you present to the world, shaped by years of conditioning, expectations, and self-protection. Then there is your authentic self\u2014the real you beneath all the layers.\n\nClose your eyes and ask yourself: \"Who am I when no one is watching? What do I believe when not influenced by others' opinions? What brings me joy that I've been afraid to pursue? What truths have I been afraid to speak?\"\n\nBeing authentic doesn't mean being reckless or harsh. It means honoring your true feelings, needs, and values. It means not betraying yourself to please others. It means living in alignment with your soul's truth.\n\nThe world doesn't need another person playing it safe and small. The world needs YOU\u2014messy, imperfect, real, beautiful YOU. Your authentic expression gives others permission to do the same.",
    affirmation: "I have the courage to show up as my authentic self in all situations.",
    prompt: "Where in your life are you not being fully authentic? What would it look like to express your true self there?",
  },
  {
    day: 16,
    title: "Trusting the Journey",
    theme: "Faith and Surrender",
    minutes: 8,
    meditation: "You are exactly where you need to be. Even if this moment feels difficult, uncertain, or not where you planned to be\u2014you are exactly where you need to be for your soul's evolution.\n\nImagine your life as a vast tapestry being woven by the universe. From your current vantage point, you can only see a few threads, and they might not make sense. Some threads are dark, some are bright. Some seem out of place. But step back, and you'd see they all create a magnificent pattern.\n\nEvery experience\u2014the joys and the heartbreaks, the successes and the failures\u2014is weaving your unique masterpiece. Trust that there is a larger design, even when you can't see it. Trust that you are being guided, even when the path is unclear.\n\nSurrender doesn't mean giving up. It means releasing the illusion of control and trusting the flow of life.",
    affirmation: "I trust the journey of my life. I am exactly where I need to be.",
    prompt: "What are you trying to control in your life? What would it feel like to surrender and trust instead?",
  },
  {
    day: 17,
    title: "Healing Your Inner Child",
    theme: "Inner Child Work",
    minutes: 8,
    meditation: "Inside you lives the child you once were\u2014with all their dreams, fears, wounds, and wonder. This inner child influences your adult life more than you realize, especially when they feel unheard or unhealed.\n\nVisualize yourself as a young child. How old are they? What are they wearing? What expression is on their face? Approach them with love and gentleness. Kneel down to their level and ask: \"What do you need? What do you want me to know?\"\n\nListen. Your inner child might need to be seen, heard, protected, or just allowed to play. They might need you to comfort them over a past hurt or celebrate a joy that was overlooked. Give them what they need now, from your adult, capable self.\n\nThis inner child is always with you. When you feel reactive, insecure, or wounded, it's often your inner child needing attention. Parent yourself with the love you needed then\u2014and still need now.",
    affirmation: "I lovingly parent my inner child and honor all parts of myself.",
    prompt: "What does your inner child need from you today? What did they need that they didn't receive growing up?",
  },
  {
    day: 18,
    title: "The Energy of Words",
    theme: "Conscious Communication",
    minutes: 8,
    meditation: "Words are spells\u2014they literally cast energy into the world and shape reality. The words you speak about yourself become your self-concept. The words you speak about others become your relationships. The words you speak about life become your experience.\n\nBring awareness to your internal dialogue today. How do you speak to yourself? With kindness or criticism? With encouragement or judgment? Now notice how you speak about your life. Do you focus on complaints or gratitude? Problems or possibilities?\n\nYour words create your world. Choose them carefully. Speak to yourself as you would to someone you deeply love. Describe your life in terms of what you want to experience, not what you fear. Replace \"I can't\" with \"I'm learning to.\" Replace \"I always fail\" with \"I'm building resilience.\"\n\nWords are creative power. Use them to build the life you want to live.",
    affirmation: "I choose words that uplift, empower, and create the reality I desire.",
    prompt: "What phrases do you repeatedly use that might be limiting you? What empowering phrases could replace them?",
  },
  {
    day: 19,
    title: "Embracing Impermanence",
    theme: "Change and Flow",
    minutes: 8,
    meditation: "Nothing in this universe is permanent\u2014not the seasons, not your circumstances, not even your cells (which completely regenerate every seven years). The only constant is change, and this is actually a profound gift.\n\nWhat you're struggling with today will shift. The pain you're feeling will transform. The situation that seems impossible will resolve or reveal its purpose. Nothing stays the same, which means nothing is truly stuck\u2014only your resistance to change creates suffering.\n\nImagine yourself as a river, constantly flowing, never the same water twice, yet always essentially yourself. You are meant to evolve, grow, release, and renew. When you stop resisting change and instead flow with it, life becomes an adventure rather than a threat.\n\nWhat if you could trust that every ending is creating space for a new beginning? What if you could release your grip and allow the current to carry you?",
    affirmation: "I flow with the changes of life, trusting that each shift serves my highest good.",
    prompt: "What change are you resisting? What might be trying to emerge if you let go?",
  },
  {
    day: 20,
    title: "Cultivating Patience",
    theme: "Divine Timing",
    minutes: 9,
    meditation: "In a world of instant gratification, patience feels countercultural. But everything meaningful takes time\u2014a seed growing into a flower, a baby developing in the womb, a friendship deepening into love, your own transformation unfolding.\n\nYou are not behind. You are not running out of time. You are exactly on schedule according to divine timing. The universe is orchestrating countless elements to align for your highest good, and this coordination requires patience.\n\nThink of something you're waiting for\u2014a goal, a relationship, healing, clarity, a breakthrough. Now release the urgency. Trust that it's coming in perfect timing. Your job isn't to force or rush\u2014it's to prepare, to stay open, to trust.\n\nThe farmer doesn't dig up the seed to check if it's growing. They water, they wait, they trust. Do the same with your dreams.",
    affirmation: "I trust in divine timing. Everything is unfolding perfectly.",
    prompt: "Where in your life are you impatient? What would it feel like to surrender to divine timing?",
  },
  {
    day: 21,
    title: "The Practice of Non-Judgment",
    theme: "Acceptance",
    minutes: 9,
    meditation: "Your mind is a judgment machine\u2014it constantly categorizes everything as good or bad, right or wrong, desirable or undesirable. This creates suffering because life simply IS, neither good nor bad until your mind labels it.\n\nToday, practice observing without judging. Notice when a judgment arises\u2014about yourself, another person, a situation\u2014and simply note: \"Judging.\" Don't judge the judging. Just notice it.\n\nWhat if you could experience life without the constant mental commentary? What if you could see yourself, others, and circumstances with neutral compassion? A cloud isn't good or bad\u2014it just is. A tree isn't succeeding or failing\u2014it's just growing. You, too, are simply being, growing, experiencing.\n\nJudgment creates separation. Acceptance creates peace. The goal isn't to approve of everything\u2014it's to stop exhausting yourself by mentally fighting with reality.",
    affirmation: "I observe life without judgment and accept what is with compassion.",
    prompt: "What do you judge most harshly\u2014yourself, others, or circumstances? What would change if you could accept instead?",
  },
  {
    day: 22,
    title: "Opening to Possibility",
    theme: "Expansive Thinking",
    minutes: 9,
    meditation: "Your mind can either be a prison or a playground, depending on whether you're trapped in \"what is\" or open to \"what could be.\" Today, we expand into possibility thinking.\n\nClose your eyes and imagine your life without any limitations\u2014no fear, no lack of resources, no judgment from others. What would you do? Who would you become? What would you create? Don't edit yourself. Let your imagination run wild.\n\nMost of what you call \"impossible\" is actually just \"improbable\" or \"scary\" or \"outside your comfort zone.\" The universe is infinite, which means possibilities are infinite. You get to choose which ones you focus on.\n\nEnergy flows where attention goes. If you focus on limitations, you'll find evidence of them. If you focus on possibilities, you'll discover opportunities everywhere. Start asking better questions: not \"Can I?\" but \"How might I?\" Not \"What if it fails?\" but \"What if it works?\"",
    affirmation: "I am open to infinite possibilities. Miracles are my natural state.",
    prompt: "If anything were possible, what would you dare to dream? Write without censoring yourself.",
  },
  {
    day: 23,
    title: "Honoring Your Boundaries",
    theme: "Healthy Limits",
    minutes: 9,
    meditation: "Boundaries are not walls to keep people out\u2014they're property lines that define where you end and others begin. They're acts of self-respect and self-love.\n\nImagine a golden circle of light surrounding you, about an arm's length in all directions. This is your sacred space, your energetic boundary. Nothing enters without your permission. No one else's emotions, expectations, or energy can cross this line unless you allow it.\n\nSetting boundaries isn't selfish\u2014it's necessary for your wellbeing. Saying \"no\" to what depletes you creates space to say \"yes\" to what nourishes you. You teach people how to treat you by what you accept.\n\nIt's okay to disappoint others if staying true to yourself requires it. You are not responsible for managing everyone else's feelings. You are responsible for honoring your own truth and needs.",
    affirmation: "I set and maintain healthy boundaries with love and without guilt.",
    prompt: "Where do you need stronger boundaries? What would you need to say \"no\" to? What makes this difficult?",
  },
  {
    day: 24,
    title: "The Gift of Stillness",
    theme: "Silence and Solitude",
    minutes: 9,
    meditation: "In the constant noise of modern life, stillness feels uncomfortable. Your mind wants to fill every silence with thoughts, every moment with activity. But it's in stillness that wisdom whispers, creativity emerges, and your soul speaks.\n\nFor the next few minutes, practice complete stillness\u2014in body and mind. Don't try to think positive thoughts or solve problems. Don't meditate \"successfully.\" Just be still.\n\nIf thoughts arise, let them pass like clouds across the sky. You are not your thoughts\u2014you are the awareness that observes thoughts. In the space between thoughts, you'll find yourself\u2014your true, essential nature beyond all doing and striving.\n\nStillness isn't emptiness\u2014it's fullness. It's where you're most connected to yourself, to the universe, to source energy. Build stillness into your daily life, even if just for three minutes. This is where transformation begins.",
    affirmation: "In stillness, I find my truest self and deepest wisdom.",
    prompt: "When do you allow yourself true stillness? What arises when you're completely quiet and alone?",
  },
  {
    day: 25,
    title: "Transforming Fear into Faith",
    theme: "From Fear to Trust",
    minutes: 9,
    meditation: "Fear and faith cannot occupy the same space. One contracts, the other expands. One focuses on what could go wrong, the other on what could go right. You get to choose which one guides you.\n\nIdentify a current fear\u2014something that keeps you up at night or holds you back. Feel where it lives in your body. Now, ask yourself: \"What would faith say about this situation? What would my highest self believe?\"\n\nFear says: \"You're not ready. You might fail. Stay small and safe.\" Faith says: \"You're being prepared. This challenge is developing your strength. Trust the process.\"\n\nBoth are stories, but faith's story serves your growth while fear's story keeps you stuck. You don't have to eliminate fear\u2014just don't let it drive. Acknowledge it, thank it for trying to protect you, and then make decisions from faith instead.",
    affirmation: "I choose faith over fear. I trust that I am guided and protected.",
    prompt: "What fear is currently guiding your decisions? What would you do if you acted from faith instead?",
  },
  {
    day: 26,
    title: "Celebrating Your Progress",
    theme: "Acknowledging Growth",
    minutes: 9,
    meditation: "You've been on this journey for 26 days now\u2014that's something to celebrate. But more than that, think about all the growth you've experienced in your life. You're not who you were a year ago, five years ago, ten years ago.\n\nYou've survived 100% of your difficult days. You've learned countless lessons. You've developed strengths you didn't know you had. You've grown in ways that would amaze your younger self.\n\nTake time to acknowledge this. Place your hand on your heart and say: \"I'm proud of you. I see how hard you've been working. I recognize your courage, your resilience, your determination. You're doing an amazing job.\"\n\nWe're so quick to notice what we haven't accomplished while ignoring how far we've come. Today, celebrate yourself. You deserve it.",
    affirmation: "I celebrate my growth and honor how far I've traveled on my journey.",
    prompt: "List 10 ways you've grown in the past year. How are you different now than you were then?",
  },
  {
    day: 27,
    title: "The Practice of Generosity",
    theme: "Giving and Service",
    minutes: 9,
    meditation: "True generosity comes from overflow, not obligation. When you give from a full cup\u2014of love, time, energy, or resources\u2014both you and the recipient are nourished.\n\nThink about the last time you gave something freely, without expecting anything in return. Maybe a compliment, your time, a listening ear, or material help. How did it feel? Generosity creates joy because it connects us\u2014it reminds us we're all part of one human family.\n\nBut generosity must start with yourself. You cannot give what you don't have. Fill yourself first\u2014with self-love, rest, nourishment, joy\u2014then share from your abundance.\n\nToday, look for opportunities to be generous in small ways: a genuine smile, letting someone go ahead of you in line, sending an encouraging text, sharing knowledge, offering help without being asked.",
    affirmation: "I give generously from my overflow and receive the joy of connection.",
    prompt: "When do you give from obligation versus genuine overflow? How can you fill your own cup first?",
  },
  {
    day: 28,
    title: "Finding Beauty in Challenges",
    theme: "Reframing Difficulty",
    minutes: 9,
    meditation: "Life's challenges aren't punishments\u2014they're invitations to evolve. Every difficulty you've faced has contributed to your strength, wisdom, and compassion. The person you've become includes all of your experiences, especially the hard ones.\n\nThink about a current challenge. Instead of asking \"Why is this happening to me?\" ask \"What is this teaching me? How is this growing me? What strength am I developing?\"\n\nJapanese culture has a practice called \"kintsugi\"\u2014repairing broken pottery with gold, making the breaks beautiful and part of the object's history. Your life is like this. Your cracks, breaks, and repairs aren't flaws\u2014they're where your gold shines through.\n\nYou're not damaged by your struggles\u2014you're gilded by them. Every scar is a testament to your resilience. Every wound that healed made you stronger. Trust that your current challenge is also creating something beautiful in you.",
    affirmation: "My challenges are shaping me into my strongest, wisest self.",
    prompt: "Think of a past difficulty that seemed terrible at the time. How did it ultimately serve your growth? How might your current challenges be doing the same?",
  },
  {
    day: 29,
    title: "Living with Purpose",
    theme: "Meaning and Direction",
    minutes: 9,
    meditation: "You were not born by accident. Your life has meaning and purpose, even if you haven't fully discovered it yet. Your purpose isn't something you need to find \"out there\"\u2014it's something you uncover by being fully yourself.\n\nAsk yourself these questions: What makes me come alive? What would I do even if no one paid me? What breaks my heart? What fills me with joy? What unique combination of skills, experiences, and passions do I have?\n\nYour purpose exists at the intersection of what you love, what you're good at, what the world needs, and what creates value. It doesn't have to be grand\u2014purpose is often found in how you show up in everyday moments.\n\nLiving with purpose means aligning your daily actions with your deeper values. It means choosing work that matters, relationships that nourish, and activities that feel meaningful. It's not about what you do\u2014it's about the energy and intention you bring to it.",
    affirmation: "I am living my purpose by being fully, authentically myself.",
    prompt: "What feels deeply meaningful to you? How can you bring more of that into your daily life?",
  },
  {
    day: 30,
    title: "Integration and Commitment",
    theme: "Moving Forward",
    minutes: 9,
    meditation: "Congratulations, beautiful soul\u2014you've completed 30 days of intentional practice. But this isn't an ending; it's a beginning. The real magic happens when you integrate these practices into your daily life.\n\nReflect on this journey. What meditations resonated most? What insights surprised you? What practices do you want to continue? Which days do you want to revisit?\n\nSpiritual growth isn't linear\u2014it's spiral. You'll revisit lessons at deeper levels. You'll forget and remember. You'll slip and return. This is all part of the process.\n\nCommit to your continued growth, but with self-compassion. You don't have to be perfect. You don't have to meditate every day. You just need to keep choosing awareness, love, and growth over autopilot, fear, and stagnation.\n\nThank yourself for showing up. Thank yourself for being willing to look inward. Thank yourself for committing to your evolution. You are exactly where you need to be, and you're doing beautifully.",
    affirmation: "I continue my journey with dedication, patience, and self-love.",
    prompt: "How have you changed over these 30 days? What practice will you commit to continuing? What's your intention for the next 30 days?",
  },
];

export function libraryToday(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0);
  const day = Math.floor((date.getTime() - start.getTime()) / 86400000);
  const idx = ((day - 1) % LIBRARY.length + LIBRARY.length) % LIBRARY.length;
  return LIBRARY[idx];
}

export function libraryByDay(n: number) {
  return LIBRARY.find((d) => d.day === n) ?? LIBRARY[0];
}
